import { type NextPage } from "next";
import Head from "next/head";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // #TODO: Figureout TRPC/useQuery
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <h1 className="bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text text-8xl font-extrabold text-transparent">
          Giffer App
        </h1>
      </main>
    </>
  );
};

export default Home;
